name: audio_toolkit_example
description: "Demonstrates how to use the audio_toolkit plugin."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # audio_toolkit:
  #   path: ../
  # audio_toolkit:
  #   git:
  #     url: https://github.com/vuduchiieu/audio_toolkit.git
  #     ref: main
  audio_toolkit: ^0.0.17
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - .env
