name: audio_toolkit
description: >
  A macOS-only Flutter plugin to record system/microphone audio and transcribe voice to text with real-time speech detection.
license: MIT
version: 0.0.10
homepage: https://github.com/vuduchiieu/audio_toolkit
repository: https://github.com/vuduchiieu/audio_toolkit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
topics:
  - audio-toolkit
  - system-audio
  - audio-processing
  - speech-to-text
  - realtime-audio
flutter:
  plugin:
    platforms:
      android:
        package: com.example.audio_toolkit
        pluginClass: AudioToolkitPlugin
      ios:
        pluginClass: AudioToolkitPlugin
      macos:
        pluginClass: AudioToolkitPlugin
      windows:
        pluginClass: AudioToolkitPluginCApi
#flutter pub publish

